### ISSUE TITLE
usbip: info: no exportable devices found on 192.168.178.***

### ISSUE THREAD

**Issue by somebuddy87** [chegewara/esp32-usbip-poc#1]
Hi, i tried with the ESP32-S3-DevKitC-1-N8R2 board. My usbip client shows the right ip and i can connect. But if i want to attach the usbip to my server it shows the following message: usbip: info: no exportable devices found on 192.168.178.***

is there a special device class to test with? maybe an usb stick or something else?

thank you!

**Comment by chegewara** [comment]
Im not sure you know the purpose of USB/IP.
You have to connect any USB device to pins 19/20 (D+/D-) on esp32S3 and the GND and +5V to power that device.
Not all device are working thou, even if usbip can detect and list, or even to mount on PC.
There is problem with pendrive, at least on my linux, because the driver on PC is trying to SetAddress, which is not implemented. 
You can test with any USB to UART, esp32 devkit or other devices.

**Comment by somebuddy87** [comment]
ok. i will try. 

on my devkit the usb pins (D+ and D-) are on Pin 20 and 21. Do i have to change these pins in one of the header files ? At the moment i try with an OTG adapter on the onboard USB port. I thought the USB port is already connected to the right pins.

![image](https://user-images.githubusercontent.com/4713347/189494333-34c5ade0-dfa4-4bdb-9f7b-3e9f34108cc1.png)

**Comment by chegewara** [comment]
This OTG port should works.
Your D+/D- are the same as for all S3 devkits, 19 and 20, you just misread it.

**Comment by somebuddy87** [comment]
ok. I will try another OTG adapter next. I connected an usb-serial adapter to the USB Port of my S3 and again **usbip: info: no exportable devices found on 192.168.178.xxx**

**Comment by somebuddy87** [comment]
it seems that there is no power delivered through the usb (OTG) port.

**Comment by somebuddy87** [comment]
After adding external 5V (VBUS) to my device it is working.
